spring:
  profiles:
    active: dev

logging:
  config: classpath:logback-assistant.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true